





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using System.ComponentModel;
using System.Xml.Serialization;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Converters;


namespace sugdemo.models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }
		
		[SitecoreInfo(SitecoreInfoType.TemplateName)]
		string TemplateName { get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		[IndexField("_id")]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
		[IndexField("_language")]
        public virtual Language Language{ get; private set; }

		[TypeConverter(typeof(IndexFieldItemUriValueConverter))]
        [XmlIgnore]
        [IndexField("_uniqueid")]
        public virtual ItemUri Uri { get; set; }
		
		[SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version
        {
            get
            {
                return Uri == null ? 0 : Uri.Version.Number;
            }
        }

		[SitecoreInfo(SitecoreInfoType.Name)]
		public virtual string ItemName { get; private set; }
		
		[SitecoreInfo(SitecoreInfoType.TemplateName)]
		public virtual string TemplateName { get; private set; }
		
		[SitecoreInfo(SitecoreInfoType.DisplayName)]
		public virtual string ItemDisplayName { get; private set; }

	}
}









namespace sugdemo.models
{


 	/// <summary>
	/// IReading Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageTypes/Reading</para>	
	/// <para>ID: 324a4376-224e-4f17-b116-773b9b783e30</para>	
	/// </summary>
	[SitecoreType(TemplateId=Reading.TemplateIdString, AutoMap=true)]
	public partial interface IReading : IGlassBase , global::sugdemo.models.IPage, global::sugdemo.models.INavigable, global::sugdemo.models.IReadingDetail
	{
	}

	
	/// <summary>
	/// Reading
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageTypes/Reading</para>	
	/// <para>ID: 324a4376-224e-4f17-b116-773b9b783e30</para>	
	/// </summary>
	[SitecoreType(TemplateId=Reading.TemplateIdString, AutoMap=true)]
	public partial class Reading  : GlassBase, IReading 
	{
	    
		public const string TemplateIdString = "324a4376-224e-4f17-b116-773b9b783e30";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Reading";

		/// <summary>
		/// The PageTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 90018ea2-156a-4919-a5b7-326f5abe7a57</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.PageTitleFieldName)]
		public virtual string PageTitle  {get; set;}

		public static readonly ID PageTitleFieldId = new ID("90018ea2-156a-4919-a5b7-326f5abe7a57");
		public const string PageTitleFieldName = "PageTitle";
			
		/// <summary>
		/// The SubTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 25257609-2fd0-4d24-97b6-2a7f032fcdbe</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.SubTitleFieldName)]
		public virtual string SubTitle  {get; set;}

		public static readonly ID SubTitleFieldId = new ID("25257609-2fd0-4d24-97b6-2a7f032fcdbe");
		public const string SubTitleFieldName = "SubTitle";
			
		/// <summary>
		/// The NavigationTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.NavigationTitleFieldName)]
		public virtual string NavigationTitle  {get; set;}

		public static readonly ID NavigationTitleFieldId = new ID("5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346");
		public const string NavigationTitleFieldName = "NavigationTitle";
			
		/// <summary>
		/// The ShowInMenu field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 3328f79c-b57b-438e-a3bc-b5438ddbee08</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.ShowInMenuFieldName)]
		public virtual bool ShowInMenu  {get; set;}

		public static readonly ID ShowInMenuFieldId = new ID("3328f79c-b57b-438e-a3bc-b5438ddbee08");
		public const string ShowInMenuFieldName = "ShowInMenu";
			
		/// <summary>
		/// The Author field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ff178202-c22f-470d-b32d-737b02745c0f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.AuthorFieldName)]
		public virtual string Author  {get; set;}

		public static readonly ID AuthorFieldId = new ID("ff178202-c22f-470d-b32d-737b02745c0f");
		public const string AuthorFieldName = "Author";
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 16643cc5-4993-434f-82ae-85a8695025f6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("16643cc5-4993-434f-82ae-85a8695025f6");
		public const string BodyFieldName = "Body";
			
		/// <summary>
		/// The Category field.
		/// <para></para>
		/// <para>Field Type: Droplink</para>		
		/// <para>Field ID: f61f6e86-2ef0-4966-b954-aaec78161b00</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Reading.CategoryFieldName)]
		public virtual Guid Category  {get; set;}

		public static readonly ID CategoryFieldId = new ID("f61f6e86-2ef0-4966-b954-aaec78161b00");
		public const string CategoryFieldName = "Category";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// IReadingListFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Folders/ReadingListFolder</para>	
	/// <para>ID: 4a4c5ce3-a949-4b55-bb9f-48c448a4d57d</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingListFolder.TemplateIdString, AutoMap=true)]
	public partial interface IReadingListFolder : IGlassBase 
	{
	}

	
	/// <summary>
	/// ReadingListFolder
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Folders/ReadingListFolder</para>	
	/// <para>ID: 4a4c5ce3-a949-4b55-bb9f-48c448a4d57d</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingListFolder.TemplateIdString, AutoMap=true)]
	public partial class ReadingListFolder  : GlassBase, IReadingListFolder 
	{
	    
		public const string TemplateIdString = "4a4c5ce3-a949-4b55-bb9f-48c448a4d57d";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "ReadingListFolder";

	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// IReadingDetail Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/ReadingDetail</para>	
	/// <para>ID: 750ed7d8-03da-41c6-957b-5ad6e06f6e8b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingDetail.TemplateIdString, AutoMap=true)]
	public partial interface IReadingDetail : IGlassBase 
	{
		/// <summary>
		/// The Author field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ff178202-c22f-470d-b32d-737b02745c0f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(ReadingDetail.AuthorFieldName)]
		string Author  {get; set;}
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 16643cc5-4993-434f-82ae-85a8695025f6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(ReadingDetail.BodyFieldName)]
		string Body  {get; set;}
			
		/// <summary>
		/// The Category field.
		/// <para></para>
		/// <para>Field Type: Droplink</para>		
		/// <para>Field ID: f61f6e86-2ef0-4966-b954-aaec78161b00</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(ReadingDetail.CategoryFieldName)]
		Guid Category  {get; set;}
			
	}

	
	/// <summary>
	/// ReadingDetail
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/ReadingDetail</para>	
	/// <para>ID: 750ed7d8-03da-41c6-957b-5ad6e06f6e8b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingDetail.TemplateIdString, AutoMap=true)]
	public partial class ReadingDetail  : GlassBase, IReadingDetail 
	{
	    
		public const string TemplateIdString = "750ed7d8-03da-41c6-957b-5ad6e06f6e8b";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "ReadingDetail";

		/// <summary>
		/// The Author field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ff178202-c22f-470d-b32d-737b02745c0f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingDetail.AuthorFieldName)]
		public virtual string Author  {get; set;}

		public static readonly ID AuthorFieldId = new ID("ff178202-c22f-470d-b32d-737b02745c0f");
		public const string AuthorFieldName = "Author";
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 16643cc5-4993-434f-82ae-85a8695025f6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingDetail.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("16643cc5-4993-434f-82ae-85a8695025f6");
		public const string BodyFieldName = "Body";
			
		/// <summary>
		/// The Category field.
		/// <para></para>
		/// <para>Field Type: Droplink</para>		
		/// <para>Field ID: f61f6e86-2ef0-4966-b954-aaec78161b00</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingDetail.CategoryFieldName)]
		public virtual Guid Category  {get; set;}

		public static readonly ID CategoryFieldId = new ID("f61f6e86-2ef0-4966-b954-aaec78161b00");
		public const string CategoryFieldName = "Category";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// ICategoryFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Folders/CategoryFolder</para>	
	/// <para>ID: 7cd793d6-3047-4d47-b5be-c7af3493e1b4</para>	
	/// </summary>
	[SitecoreType(TemplateId=CategoryFolder.TemplateIdString, AutoMap=true)]
	public partial interface ICategoryFolder : IGlassBase 
	{
	}

	
	/// <summary>
	/// CategoryFolder
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Folders/CategoryFolder</para>	
	/// <para>ID: 7cd793d6-3047-4d47-b5be-c7af3493e1b4</para>	
	/// </summary>
	[SitecoreType(TemplateId=CategoryFolder.TemplateIdString, AutoMap=true)]
	public partial class CategoryFolder  : GlassBase, ICategoryFolder 
	{
	    
		public const string TemplateIdString = "7cd793d6-3047-4d47-b5be-c7af3493e1b4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "CategoryFolder";

	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// IHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageElements/Wrapper/Header</para>	
	/// <para>ID: 8f1c173c-517c-4420-8039-4ad9fecdad09</para>	
	/// </summary>
	[SitecoreType(TemplateId=Header.TemplateIdString, AutoMap=true)]
	public partial interface IHeader : IGlassBase 
	{
		/// <summary>
		/// The BackgroundImage field.
		/// <para></para>
		/// <para>Field Type: Image</para>		
		/// <para>Field ID: f39a568f-f2b0-47c9-92b9-fa6e49137ce4</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Header.BackgroundImageFieldName)]
		Image BackgroundImage  {get; set;}
			
		/// <summary>
		/// The Heading field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 4d8af3ce-0827-4ff3-a77f-6cbb991a64dd</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Header.HeadingFieldName)]
		string Heading  {get; set;}
			
		/// <summary>
		/// The Subtitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: aac6b320-66f9-444d-bfa5-42bf8e7e43e1</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Header.SubtitleFieldName)]
		string Subtitle  {get; set;}
			
	}

	
	/// <summary>
	/// Header
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageElements/Wrapper/Header</para>	
	/// <para>ID: 8f1c173c-517c-4420-8039-4ad9fecdad09</para>	
	/// </summary>
	[SitecoreType(TemplateId=Header.TemplateIdString, AutoMap=true)]
	public partial class Header  : GlassBase, IHeader 
	{
	    
		public const string TemplateIdString = "8f1c173c-517c-4420-8039-4ad9fecdad09";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Header";

		/// <summary>
		/// The BackgroundImage field.
		/// <para></para>
		/// <para>Field Type: Image</para>		
		/// <para>Field ID: f39a568f-f2b0-47c9-92b9-fa6e49137ce4</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Header.BackgroundImageFieldName)]
		public virtual Image BackgroundImage  {get; set;}

		public static readonly ID BackgroundImageFieldId = new ID("f39a568f-f2b0-47c9-92b9-fa6e49137ce4");
		public const string BackgroundImageFieldName = "BackgroundImage";
			
		/// <summary>
		/// The Heading field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 4d8af3ce-0827-4ff3-a77f-6cbb991a64dd</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Header.HeadingFieldName)]
		public virtual string Heading  {get; set;}

		public static readonly ID HeadingFieldId = new ID("4d8af3ce-0827-4ff3-a77f-6cbb991a64dd");
		public const string HeadingFieldName = "Heading";
			
		/// <summary>
		/// The Subtitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: aac6b320-66f9-444d-bfa5-42bf8e7e43e1</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Header.SubtitleFieldName)]
		public virtual string Subtitle  {get; set;}

		public static readonly ID SubtitleFieldId = new ID("aac6b320-66f9-444d-bfa5-42bf8e7e43e1");
		public const string SubtitleFieldName = "Subtitle";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// ICategory Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Category</para>	
	/// <para>ID: 9199e2f0-c861-48cb-b8b8-992668354d47</para>	
	/// </summary>
	[SitecoreType(TemplateId=Category.TemplateIdString, AutoMap=true)]
	public partial interface ICategory : IGlassBase 
	{
		/// <summary>
		/// The CategoryName field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5b10e94f-7fe0-4c30-9fe1-d5f45954cda0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Category.CategoryNameFieldName)]
		string CategoryName  {get; set;}
			
	}

	
	/// <summary>
	/// Category
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Category</para>	
	/// <para>ID: 9199e2f0-c861-48cb-b8b8-992668354d47</para>	
	/// </summary>
	[SitecoreType(TemplateId=Category.TemplateIdString, AutoMap=true)]
	public partial class Category  : GlassBase, ICategory 
	{
	    
		public const string TemplateIdString = "9199e2f0-c861-48cb-b8b8-992668354d47";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Category";

		/// <summary>
		/// The CategoryName field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5b10e94f-7fe0-4c30-9fe1-d5f45954cda0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Category.CategoryNameFieldName)]
		public virtual string CategoryName  {get; set;}

		public static readonly ID CategoryNameFieldId = new ID("5b10e94f-7fe0-4c30-9fe1-d5f45954cda0");
		public const string CategoryNameFieldName = "CategoryName";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// IReadingList Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageTypes/ReadingList</para>	
	/// <para>ID: 97da8901-21c2-4099-b173-c25a1c18e58a</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingList.TemplateIdString, AutoMap=true)]
	public partial interface IReadingList : IGlassBase , global::sugdemo.models.IPage, global::sugdemo.models.INavigable
	{
	}

	
	/// <summary>
	/// ReadingList
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/PageTypes/ReadingList</para>	
	/// <para>ID: 97da8901-21c2-4099-b173-c25a1c18e58a</para>	
	/// </summary>
	[SitecoreType(TemplateId=ReadingList.TemplateIdString, AutoMap=true)]
	public partial class ReadingList  : GlassBase, IReadingList 
	{
	    
		public const string TemplateIdString = "97da8901-21c2-4099-b173-c25a1c18e58a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "ReadingList";

		/// <summary>
		/// The PageTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 90018ea2-156a-4919-a5b7-326f5abe7a57</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingList.PageTitleFieldName)]
		public virtual string PageTitle  {get; set;}

		public static readonly ID PageTitleFieldId = new ID("90018ea2-156a-4919-a5b7-326f5abe7a57");
		public const string PageTitleFieldName = "PageTitle";
			
		/// <summary>
		/// The SubTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 25257609-2fd0-4d24-97b6-2a7f032fcdbe</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingList.SubTitleFieldName)]
		public virtual string SubTitle  {get; set;}

		public static readonly ID SubTitleFieldId = new ID("25257609-2fd0-4d24-97b6-2a7f032fcdbe");
		public const string SubTitleFieldName = "SubTitle";
			
		/// <summary>
		/// The NavigationTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingList.NavigationTitleFieldName)]
		public virtual string NavigationTitle  {get; set;}

		public static readonly ID NavigationTitleFieldId = new ID("5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346");
		public const string NavigationTitleFieldName = "NavigationTitle";
			
		/// <summary>
		/// The ShowInMenu field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 3328f79c-b57b-438e-a3bc-b5438ddbee08</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(ReadingList.ShowInMenuFieldName)]
		public virtual bool ShowInMenu  {get; set;}

		public static readonly ID ShowInMenuFieldId = new ID("3328f79c-b57b-438e-a3bc-b5438ddbee08");
		public const string ShowInMenuFieldName = "ShowInMenu";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// INavigable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Navigable</para>	
	/// <para>ID: bf41068c-4e3e-4ad4-8efd-ef9585a3a38f</para>	
	/// </summary>
	[SitecoreType(TemplateId=Navigable.TemplateIdString, AutoMap=true)]
	public partial interface INavigable : IGlassBase 
	{
		/// <summary>
		/// The NavigationTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Navigable.NavigationTitleFieldName)]
		string NavigationTitle  {get; set;}
			
		/// <summary>
		/// The ShowInMenu field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 3328f79c-b57b-438e-a3bc-b5438ddbee08</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Navigable.ShowInMenuFieldName)]
		bool ShowInMenu  {get; set;}
			
	}

	
	/// <summary>
	/// Navigable
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Navigable</para>	
	/// <para>ID: bf41068c-4e3e-4ad4-8efd-ef9585a3a38f</para>	
	/// </summary>
	[SitecoreType(TemplateId=Navigable.TemplateIdString, AutoMap=true)]
	public partial class Navigable  : GlassBase, INavigable 
	{
	    
		public const string TemplateIdString = "bf41068c-4e3e-4ad4-8efd-ef9585a3a38f";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Navigable";

		/// <summary>
		/// The NavigationTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Navigable.NavigationTitleFieldName)]
		public virtual string NavigationTitle  {get; set;}

		public static readonly ID NavigationTitleFieldId = new ID("5c5dee1e-2dd2-4c65-9b6f-af55cbc5f346");
		public const string NavigationTitleFieldName = "NavigationTitle";
			
		/// <summary>
		/// The ShowInMenu field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 3328f79c-b57b-438e-a3bc-b5438ddbee08</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Navigable.ShowInMenuFieldName)]
		public virtual bool ShowInMenu  {get; set;}

		public static readonly ID ShowInMenuFieldId = new ID("3328f79c-b57b-438e-a3bc-b5438ddbee08");
		public const string ShowInMenuFieldName = "ShowInMenu";
			
	
	}
}











namespace sugdemo.models
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Page</para>	
	/// <para>ID: dc5969e5-d293-4ea4-91de-c0a6cdb17fb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=Page.TemplateIdString, AutoMap=true)]
	public partial interface IPage : IGlassBase 
	{
		/// <summary>
		/// The PageTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 90018ea2-156a-4919-a5b7-326f5abe7a57</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Page.PageTitleFieldName)]
		string PageTitle  {get; set;}
			
		/// <summary>
		/// The SubTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 25257609-2fd0-4d24-97b6-2a7f032fcdbe</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Page.SubTitleFieldName)]
		string SubTitle  {get; set;}
			
	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/SUGDemo/Interfaces/Page</para>	
	/// <para>ID: dc5969e5-d293-4ea4-91de-c0a6cdb17fb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=Page.TemplateIdString, AutoMap=true)]
	public partial class Page  : GlassBase, IPage 
	{
	    
		public const string TemplateIdString = "dc5969e5-d293-4ea4-91de-c0a6cdb17fb4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Page";

		/// <summary>
		/// The PageTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 90018ea2-156a-4919-a5b7-326f5abe7a57</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Page.PageTitleFieldName)]
		public virtual string PageTitle  {get; set;}

		public static readonly ID PageTitleFieldId = new ID("90018ea2-156a-4919-a5b7-326f5abe7a57");
		public const string PageTitleFieldName = "PageTitle";
			
		/// <summary>
		/// The SubTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 25257609-2fd0-4d24-97b6-2a7f032fcdbe</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Page.SubTitleFieldName)]
		public virtual string SubTitle  {get; set;}

		public static readonly ID SubTitleFieldId = new ID("25257609-2fd0-4d24-97b6-2a7f032fcdbe");
		public const string SubTitleFieldName = "SubTitle";
			
	
	}
}

